#ifndef __languages_H
#define __languages_H

#include "includes.h"
#include "main.h"


#define	LNG_LANGS_COUNT		(uint8_t)2


typedef enum 
{
	LSTR____ = (uint32_t)0,
	LSTR_TESTSTRING,

	LSTR_JANUARY,
	LSTR_FEBRUARY,
	LSTR_MARCH,
	LSTR_APRIL,
	LSTR_MAY,
	LSTR_JUNE,
	LSTR_JULY,
	LSTR_AUGUST,
	LSTR_SEPTEMBER,
	LSTR_OCTOBER,
	LSTR_NOVEMBER,
	LSTR_DECEMBER,
	
	LSTR_SHORTHOUR,
	LSTR_SHORTMINUTE,
	LSTR_SHORTSECOND,
	LSTR_SHORTMILLIMETERS,
	LSTR_SHORTMILLILITERS,
	LSTR_MM_MIN,
	LSTR_MM_SEC,
	LSTR_MM_SEC2,
	LSTR_KB,
	LSTR_MB,
	
	LSTR_OK,
	LSTR_CANCEL,
	LSTR_YES,
	LSTR_NO,

	LSTR_10MM,
	LSTR_1MM,
	LSTR_02MM,
	LSTR_005MM,
	
	LSTR_BACK,
	LSTR_MAINMENU,
	LSTR_PRINT,
	LSTR_SERVICE,
	LSTR_INFO,
	LSTR_LANGUAGE,
	LSTR_MOVEZ,
	LSTR_UVTEST,
	LSTR_SETTINGS_SHORT,
	LSTR_SETTINGS_FULL,
	
	LSTR_VERSION,
	LSTR_LIGHT_TIME,
	LSTR_DISPLAY_TIME,
	LSTR_FAN_TIME,
	LSTR_TOTALPRINT_TIME,
	LSTR_URL,
	LSTR_UIAUTHOR,
	
	LSTR_MOVEHOME,
	LSTR_SETZ0,
	LSTR_STOPMOVE,
	
	LSTR_WARNING,
	LSTR_ERROR,
	LSTR_CONFIRM_ACT,
	LSTR_WAIT,
	LSTR_COMPLETED,
	LSTR_HOME_FIRST,
	LSTR_ENDSTOP_NOT_FOUND,
	LSTR_ENDSTOP_ERROR,
	LSTR_CFGFILE_LOAD_QUEST,
	LSTR_CFGFILE_LOADING,
	LSTR_FILE_OPEN_ERROR,
	LSTR_CFGFILE_LOADED,
	LSTR_UNKNOWN_SECTNAME_IN_CFG,
	LSTR_UNKNOWN_PARAMNAME_IN_CFG,
	LSTR_INVALID_PARAMVAL_IN_CFG,
	LSTR_SURE_NO_MODEL_ON_PLATFORM,
	LSTR_LIFT_ON_PAUSE,
	LSTR_BUZZER,
	LSTR_ON,
	LSTR_OFF,
	LSTR_SAVING_SETTINGS,
	LSTR_AC,
	LSTR_SET_CURRENT_Z0_QUEST,
	LSTR_SET_CURRENT_Z0_SUCCESS,
	LSTR_FILEVIEW_CAPTION,
	LSTR_FILESIZE,
	LSTR_FILETIME,
	LSTR_TOTAL_LAYERS,
	LSTR_PRINT_TIME,
	LSTR_LAYER_THICKNESS,
	LSTR_ANTIALIASING,
	LSTR_TIME_LIGHT,
	LSTR_TIME_BOTTOM_LIGHT,
	LSTR_TIME_PAUSE_LIGHT,
	LSTR_LIFT_HEIGHT,
	LSTR_LIFT_SPEED,
	LSTR_DROP_SPEED,
	LSTR_RESIN_VOLUME,
	LSTR_IND_LAYERS_SETTINGS,



	_LSTR_LASTITEM,

	_LSTR_MAXITEM = 0xFFFFFFFF
} LNG_STRING_ID;


typedef struct
{
	char		*name;
	char		**strings;
} LNG_LANGUAGE;




char*		LANG_GetString(LNG_STRING_ID id);
char*		LANG_GetLanguageName(uint8_t lang);
void		LANG_SetLanguage(uint8_t lang);
uint8_t		LANG_GetLanduagesCount();





#endif /*__languages_H */

